# The Docker image that will be used to build your app
image: "image: node:12.17.0"
# Functions that should be executed before the build script is run
before_script:
  - npm install
  - npm run build
